name: "Run Tests"

on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - "*.md"
      - "*.example"
      - ".gitignore"

jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.11", "3.12", "3.13"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Core Unit Tests
        env:
          UV_SYSTEM_PYTHON: 1
        run: |
          uv pip install "snitch @ ."
          pytest -v tests/
